CREATE PROCEDURE [val].[OEExists]
	
	@oeId BIGINT,
	@exists BIT OUTPUT

AS

SET NOCOUNT ON

SET @exists = CASE WHEN EXISTS (
	SELECT	1
	FROM	val.VALIDATION_OE v
	WHERE	v.id = @oeId
) THEN 1 ELSE 0 END