CREATE PROCEDURE [val].[OEIsUsed]
	
	@oeId BIGINT,
	@isUsed BIT OUTPUT

AS

SET NOCOUNT ON

SET @isUsed = CASE WHEN EXISTS (
	SELECT	1
	FROM	val.VALIDATION_SCENARIO_OE_LINK v
	WHERE	v.validation_oe_id = @oeId
) THEN 1 ELSE 0 END