CREATE TABLE [ref].[CRYPTO_ALGORITHM_FAMILY] (
    [id]          BIGINT         NOT NULL,
    [name]        NVARCHAR (128) NOT NULL,
    [header_text] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CRYPTO_ALGORITHM_FAMILY] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_CRYPTO_ALGORITHM_FAMILY_NAME] UNIQUE NONCLUSTERED ([name] ASC)
);

