CREATE TABLE [ref].[CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK] (
    [id]                   BIGINT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [acv_version_id]       INT    NOT NULL,
    [protocol_id]          BIGINT NOT NULL,
    [capability_parent_id] BIGINT NULL,
    [vector_parent_id]     BIGINT NULL,
    [group_parent_id]      BIGINT NULL,
    [value_parent_id]      BIGINT NULL,
    CONSTRAINT [PK_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK_VERSION_PROTOCOL] UNIQUE NONCLUSTERED ([acv_version_id] ASC, [protocol_id] ASC)
);

