using System;
public class GenValRequestJob
{
    /// <summary>
    /// Unique identifier for tracking this job (generated by client).
    /// </summary>
    public Guid JobId { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The type of operation to perform, e.g., "generate", "validate", "get-supported-algorithms".
    /// </summary>
    public string Operation { get; set; }

    /// <summary>
    /// Optional: Vector Set ID (used for ACVP testing if applicable).
    /// </summary>
    public int? VsId { get; set; }

    /// <summary>
    /// The payload required to process this operation. Serialized JSON string.
    /// </summary>
    public string Payload { get; set; }

    /// <summary>
    /// Optional timestamp for when the job was submitted.
    /// </summary>
    public DateTime SubmittedAtUtc { get; set; } = DateTime.UtcNow;
}