using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NIST.CVP.ACVTS.Libraries.Generation.Core;
using NIST.CVP.ACVTS.Libraries.Generation.Core.Async;
using NIST.CVP.ACVTS.Libraries.Math;
using NIST.CVP.ACVTS.Libraries.Oracle.Abstractions;
using NIST.CVP.ACVTS.Libraries.Oracle.Abstractions.ParameterTypes.Xmss;
using NIST.CVP.ACVTS.Libraries.Oracle.Abstractions.ResultTypes;
using NLog;

namespace NIST.CVP.ACVTS.Libraries.Generation.XMSS.SP800_208.SigGen;

public class TestCaseGeneratorAft : ITestCaseGeneratorWithPrep<TestGroup, TestCase>
{
    private readonly IOracle _oracle;
    private ShuffleQueue<int> _messageLengths;
    private ShuffleQueue<int> _idx;

    public int NumberOfTestCasesToGenerate => 10;

    public TestCaseGeneratorAft(IOracle oracle)
    {
        _oracle = oracle;
    }

    public GenerateResponse PrepareGenerator(TestGroup group, bool isSample)
    {
        var messageLengths = new List<int>();
        messageLengths.AddRange(group.MessageLength.GetDomainMinMaxAsEnumerable());
        messageLengths.AddRange(group.MessageLength.GetRandomValues(_ => true, NumberOfTestCasesToGenerate - 2));

        _messageLengths = new ShuffleQueue<int>(messageLengths);
        _idx = new ShuffleQueue<int>(Enumerable.Range(0, 32).ToList());

        return new GenerateResponse();
    }

    public async Task<TestCaseGenerateResponse<TestGroup, TestCase>> GenerateAsync(TestGroup group, bool isSample, int caseNo = -1)
    {
        var param = new XmssSignatureParameters
        {
            MessageLength = _messageLengths.Pop(),
            Idx = _idx.Pop()    // Idx ensures that no leaf is used multiple times
        };

        try
        {
            TestCase testCase = null;
            XmssSignatureResult result = null;
            if (isSample)
            {
                // Rely on tree generated by the group
                param.XmssKeyPair = group.KeyPair;
                result = await _oracle.GetXmssSignatureCaseAsync(param);
                testCase = new TestCase { Message = result.Message, Signature = result.Signature, MessageLength = param.MessageLength };
            }
            else
            {
                // Rely on tree generated by the client
                result = await _oracle.GetDeferredXmssSignatureCaseAsync(param);
                testCase = new TestCase { Message = result.Message, MessageLength = param.MessageLength };
            }

            return new TestCaseGenerateResponse<TestGroup, TestCase>(testCase);
        }
        catch (Exception ex)
        {
            ThisLogger.Error(ex);
            return new TestCaseGenerateResponse<TestGroup, TestCase>($"Error generating case: {ex.Message}");
        }
    }

    private static ILogger ThisLogger => LogManager.GetCurrentClassLogger();
}
