CREATE TABLE [dbo].[ACVPRoles] (
    [ACVPRoleId]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [RoleName]  NVARCHAR (64) NOT NULL,
    [RoleGroup] NVARCHAR (64) CONSTRAINT [DF_ACVPRoles_RoleGroup] DEFAULT ('Roles') NOT NULL,
    CONSTRAINT [PK_ACVPRoles] PRIMARY KEY CLUSTERED ([ACVPRoleId] ASC)
);

