CREATE TABLE [dbo].[ACVPUserRoles] (
    [ACVPUserRoleId]      BIGINT IDENTITY (1, 1) NOT NULL,
    [ACVPRoleId] BIGINT NOT NULL,
    [ACVPUserId] BIGINT NOT NULL,
    CONSTRAINT [PK_ACVPUserRoles] PRIMARY KEY CLUSTERED ([ACVPUserRoleId] ASC),
    CONSTRAINT [FK_ACVPUserRoles_ACVPRoles] FOREIGN KEY ([ACVPRoleId]) REFERENCES [dbo].[ACVPRoles] ([ACVPRoleId]),
    CONSTRAINT [FK_ACVPUserRoles_ACVPUsers] FOREIGN KEY ([ACVPUserId]) REFERENCES [dbo].[ACVPUsers] ([ACVPUserId]),
    CONSTRAINT [UQ_ACVPUserRoles_Role_User] UNIQUE NONCLUSTERED ([ACVPRoleId] ASC, [ACVPUserId] ASC)
);

