CREATE TABLE [dbo].[OEs] (
    [OEId]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (2048) NOT NULL,
    [ITAR] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_OEs] PRIMARY KEY CLUSTERED ([OEId] ASC)
);

