using NIST.CVP.ACVTS.Libraries.Crypto.Common.KAS.KDA.KdfOneStep;
using NIST.CVP.ACVTS.Libraries.Math;

namespace NIST.CVP.ACVTS.Libraries.Crypto.Common.KAS.KDA
{
    public class KdfResult
    {
        /// <summary>
        /// The Derived Key Generated by <see cref="IKdfOneStep.DeriveKey"/>
        /// </summary>
        public BitString DerivedKey { get; }

        /// <summary>
        /// Was the generation successful?
        /// </summary>
        public bool Success => string.IsNullOrEmpty(ErrorMessage);

        /// <summary>
        /// Message associated to generation attempt
        /// </summary>
        public string ErrorMessage { get; }

        public KdfResult(BitString derivedKey)
        {
            DerivedKey = derivedKey;
        }

        public KdfResult(string errorMessage)
        {
            ErrorMessage = errorMessage;
        }
    }
}
