export enum APIAction {
  Unknown = 'Unknown',
  CreateDependency = 'CreateDependency',
  UpdateDependency = 'UpdateDependency',
  DeleteDependency = 'DeleteDependency',
  CreateImplementation = 'CreateImplementation',
  UpdateImplementation = 'UpdateImplementation',
  DeleteImplementation = 'DeleteImplementation',
  CreateOE = 'CreateOE',
  UpdateOE = 'UpdateOE',
  DeleteOE = 'DeleteOE',
  CreatePerson = 'CreatePerson',
  UpdatePerson = 'UpdatePerson',
  DeletePerson = 'DeletePerson',
  CreateVendor = 'CreateVendor',
  UpdateVendor = 'UpdateVendor',
  DeleteVendor = 'DeleteVendor',
  RegisterTestSession = 'RegisterTestSession',
  CancelTestSession = 'CancelTestSession',
  CertifyTestSession = 'CertifyTestSession',
  SubmitVectorSetResults = 'SubmitVectorSetResults',
  CancelVectorSet = 'CancelVectorSet'
}
