CREATE TABLE [val].[VALIDATION_SOURCE] (
    [id]     INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [name]   NVARCHAR (32) NOT NULL,
    [prefix] NVARCHAR (16) NULL,
    CONSTRAINT [PK_VALIDATION_SOURCE] PRIMARY KEY CLUSTERED ([id] ASC)
);

