CREATE TABLE [val].[VALIDATION_OE] (
    [id]   BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [name] NVARCHAR (2048) NOT NULL,
    CONSTRAINT [PK_VALIDATION_OE] PRIMARY KEY CLUSTERED ([id] ASC)
);

