CREATE TABLE [val].[VALIDATION_SCENARIO_ALGORITHM] (
    [id]           BIGINT IDENTITY (1, 1) NOT NULL,
    [algorithm_id] BIGINT NOT NULL,
    [scenario_id]  BIGINT NOT NULL,
    CONSTRAINT [PK_VALIDATION_SCENARIO_ALGORITHM] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_VALIDATION_SCENARIO_ALGORITHM_ALGORITHM_ID] FOREIGN KEY ([algorithm_id]) REFERENCES [ref].[CRYPTO_ALGORITHM] ([id]),
    CONSTRAINT [FK_VALIDATION_SCENARIO_ALGORITHM_SCENARIO_ID] FOREIGN KEY ([scenario_id]) REFERENCES [val].[VALIDATION_SCENARIO] ([id])
);

