CREATE TABLE [val].[VALIDATION_SCENARIO] (
    [id]        BIGINT IDENTITY (1, 1) NOT NULL,
    [record_id] BIGINT NOT NULL,
    CONSTRAINT [PK_VALIDATION_SCENARIO] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_VALIDATION_SCENARIO_RECORD_ID] FOREIGN KEY ([record_id]) REFERENCES [val].[VALIDATION_RECORD] ([id])
);

