CREATE TABLE [val].[VALIDATION_PREREQUISITE] (
    [id]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [scenario_algorithm_id] BIGINT          NOT NULL,
    [record_id]             BIGINT          NOT NULL,
    [requirement]           NVARCHAR (2048) NOT NULL,
    CONSTRAINT [PK_VALIDATION_PREREQUISITE] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_VALIDATION_PREREQUISITE_RECORD_ID] FOREIGN KEY ([record_id]) REFERENCES [val].[VALIDATION_RECORD] ([id]),
    CONSTRAINT [FK_VALIDATION_PREREQUISITE_SCENARIO_ALGORITHM_ID] FOREIGN KEY ([scenario_algorithm_id]) REFERENCES [val].[VALIDATION_SCENARIO_ALGORITHM] ([id])
);

