CREATE TABLE [val].[VALIDATION_OE_DEPENDENCY_LINK] (
    [validation_oe_id] BIGINT NOT NULL,
    [dependency_id]    BIGINT NOT NULL,
    CONSTRAINT [PK_VALIDATION_OE_DEPENDENCY_LINK] PRIMARY KEY CLUSTERED ([validation_oe_id] ASC, [dependency_id] ASC),
    CONSTRAINT [FK_VALIDATION_OE_DEPENDENCY_LINK_DEPENDENCY_ID] FOREIGN KEY ([dependency_id]) REFERENCES [val].[VALIDATION_OE_DEPENDENCY] ([id]),
    CONSTRAINT [FK_VALIDATION_OE_DEPENDENCY_LINK_VALIDATION_OE_ID] FOREIGN KEY ([validation_oe_id]) REFERENCES [val].[VALIDATION_OE] ([id])
);

