CREATE TABLE [val].[VALIDATION_SCENARIO_OE_LINK] (
    [scenario_id]      BIGINT NOT NULL,
    [validation_oe_id] BIGINT NOT NULL,
    CONSTRAINT [PK_VALIDATION_SCENARIO_OE_LINK_SCENARIO_OE_ID] PRIMARY KEY CLUSTERED ([scenario_id] ASC, [validation_oe_id] ASC),
    CONSTRAINT [FK_VALIDATION_SCENARIO_OE_LINK_SCENARIO_ID] FOREIGN KEY ([scenario_id]) REFERENCES [val].[VALIDATION_SCENARIO] ([id]),
    CONSTRAINT [FK_VALIDATION_SCENARIO_OE_LINK_VALIDATION_OE_ID] FOREIGN KEY ([validation_oe_id]) REFERENCES [val].[VALIDATION_OE] ([id])
);

