CREATE TABLE [dbo].[OEs] (
    [OEId] BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name] NVARCHAR (2048) NOT NULL,
    CONSTRAINT [PK_OEs] PRIMARY KEY CLUSTERED ([OEId] ASC)
);

