using External = NIST.CVP.Algorithms.External;

namespace NIST.CVP.Algorithms.Persisted
{
	public static class PersistedAlgorithmFactory
	{
		public static IPersistedAlgorithm GetPersistedAlgorithm(External.IExternalAlgorithm externalAlgorithm)
		{
			//Get the type by a big old switch
			return externalAlgorithm switch
			{
				External.AES_CBC x => new AES_CBC(x),
				External.AES_CBC_CS1 x => new AES_CBC_CS1(x),
				External.AES_CBC_CS2 x => new AES_CBC_CS2(x),
				External.AES_CBC_CS3 x => new AES_CBC_CS3(x),
				External.AES_CCM x => new AES_CCM(x),
				External.AES_CFB1 x => new AES_CFB1(x),
				External.AES_CFB128 x => new AES_CFB128(x),
				External.AES_CFB8 x => new AES_CFB8(x),
				External.AES_CTR x => new AES_CTR(x),
				External.AES_ECB x => new AES_ECB(x),
				External.AES_FF1 x => new AES_FF1(x),
				External.AES_FF3_1 x => new AES_FF3_1(x),
				External.AES_GCM x => new AES_GCM(x),
				External.AES_GCM_SIV x => new AES_GCM_SIV(x),
				External.AES_GMAC x => new AES_GMAC(x),
				External.AES_KW x => new AES_KW(x),
				External.AES_KWP x => new AES_KWP(x),
				External.AES_OFB x => new AES_OFB(x),
				External.AES_XPN x => new AES_XPN(x),
				External.AES_XTS x => new AES_XTS(x),
				External.AES_CMAC x => new AES_CMAC(x),
				External.CounterDRBG x => new CounterDRBG(x),
				External.CSHAKE_128 x => new CSHAKE_128(x),
				External.CSHAKE_256 x => new CSHAKE_256(x),
				External.DeterministicECDSASigGen186_5 x => new DeterministicECDSASigGen186_5(x),
				External.DSAKeyGen186_4 x => new DSAKeyGen186_4(x),
				External.DSAPQGGen186_4 x => new DSAPQGGen186_4(x),
				External.DSAPQGVer186_4 x => new DSAPQGVer186_4(x),
				External.DSASigGen186_4 x => new DSASigGen186_4(x),
				External.DSASigVer186_4 x => new DSASigVer186_4(x),
				External.ECDSAKeyGen186_4 x => new ECDSAKeyGen186_4(x),
				External.ECDSAKeyVer186_4 x => new ECDSAKeyVer186_4(x),
				External.ECDSASigGen186_4 x => new ECDSASigGen186_4(x),
				External.ECDSASigVer186_4 x => new ECDSASigVer186_4(x),
				External.ECDSAKeyGen186_5 x => new ECDSAKeyGen186_5(x),
				External.ECDSAKeyVer186_5 x => new ECDSAKeyVer186_5(x),
				External.ECDSASigGen186_5 x => new ECDSASigGen186_5(x),
				External.ECDSASigVer186_5 x => new ECDSASigVer186_5(x),
				External.EDDSAKeyGen x => new EDDSAKeyGen(x),
				External.EDDSAKeyVer x => new EDDSAKeyVer(x),
				External.EDDSASigGen x => new EDDSASigGen(x),
				External.EDDSASigVer x => new EDDSASigVer(x),
				External.HashDRBG x => new HashDRBG(x),
				External.HMAC_DRBG x => new HMAC_DRBG(x),
				External.HMAC_SHA_1 x => new HMAC_SHA_1(x),
				External.HMAC_SHA2_224 x => new HMAC_SHA2_224(x),
				External.HMAC_SHA2_256 x => new HMAC_SHA2_256(x),
				External.HMAC_SHA2_384 x => new HMAC_SHA2_384(x),
				External.HMAC_SHA2_512 x => new HMAC_SHA2_512(x),
				External.HMAC_SHA2_512224 x => new HMAC_SHA2_512224(x),
				External.HMAC_SHA2_512256 x => new HMAC_SHA2_512256(x),
				External.HMAC_SHA3_224 x => new HMAC_SHA3_224(x),
				External.HMAC_SHA3_256 x => new HMAC_SHA3_256(x),
				External.HMAC_SHA3_384 x => new HMAC_SHA3_384(x),
				External.HMAC_SHA3_512 x => new HMAC_SHA3_512(x),
				External.KAS_ECC x => new KAS_ECC(x),
				External.KAS_ECC_Component x => new KAS_ECC_Component(x),
				External.KAS_ECC_CDH x => new KAS_ECC_CDH(x),
				External.KAS_ECC_SP800_56Ar3 x => new KAS_ECC_SP800_56Ar3(x),
				External.KAS_FFC x => new KAS_FFC(x),
				External.KAS_FFC_Component x => new KAS_FFC_Component(x),
				External.KAS_FFC_SP800_56Ar3 x => new KAS_FFC_SP800_56Ar3(x),
				External.KAS_IFC x => new KAS_IFC(x),
				External.KDF x => new KDF(x),
				External.KDF_ANSIX942 x => new KDF_ANSIX942(x),
				External.KDF_ANSIX963 x => new KDF_ANSIX963(x),
				External.KDF_IKEv1 x => new KDF_IKEv1(x),
				External.KDF_IKEv2 x => new KDF_IKEv2(x),
				External.KDF_PBKDF x => new KDF_PBKDF(x),
				External.KDF_SNMP x => new KDF_SNMP(x),
				External.KDF_SRTP x => new KDF_SRTP(x),
				External.KDF_SSH x => new KDF_SSH(x),
				External.KDF_TLS x => new KDF_TLS(x),
				External.KDF_TPM x => new KDF_TPM(x),
				External.KMAC_128 x => new KMAC_128(x),
				External.KMAC_256 x => new KMAC_256(x),
				External.KTS_IFC x => new KTS_IFC(x),
				External.ParallelHash_128 x => new ParallelHash_128(x),
				External.ParallelHash_256 x => new ParallelHash_256(x),
				External.RSADecryptionPrimitive x => new RSADecryptionPrimitive(x),
				External.RSASignaturePrimitive x => new RSASignaturePrimitive(x),
				External.RSAKeyGen186_2 x => new RSAKeyGen186_2(x),
				External.RSAKeyGen186_4 x => new RSAKeyGen186_4(x),
				External.RSAKeyGen186_5 x => new RSAKeyGen186_5(x),
				External.RSASigGen186_2 x => new RSASigGen186_2(x),
				External.RSASigGen186_4 x => new RSASigGen186_4(x),
				External.RSASigGen186_5 x => new RSASigGen186_5(x),
				External.RSASigVer186_2 x => new RSASigVer186_2(x),
				External.RSASigVer186_4 x => new RSASigVer186_4(x),
				External.RSASigVer186_5 x => new RSASigVer186_5(x),
				External.SafePrimesKeyGen x => new SafePrimesKeyGen(x),
				External.SafePrimesKeyVer x => new SafePrimesKeyVer(x),
				External.SHA_1 x => new SHA_1(x),
				External.SHA2_224 x => new SHA2_224(x),
				External.SHA2_256 x => new SHA2_256(x),
				External.SHA2_384 x => new SHA2_384(x),
				External.SHA2_512 x => new SHA2_512(x),
				External.SHA2_512224 x => new SHA2_512224(x),
				External.SHA2_512256 x => new SHA2_512256(x),
				External.SHA3_224 x => new SHA3_224(x),
				External.SHA3_256 x => new SHA3_256(x),
				External.SHA3_384 x => new SHA3_384(x),
				External.SHA3_512 x => new SHA3_512(x),
				External.SHAKE_128 x => new SHAKE_128(x),
				External.SHAKE_256 x => new SHAKE_256(x),
				External.TDES_CBC x => new TDES_CBC(x),
				External.TDES_CBCI x => new TDES_CBCI(x),
				External.TDES_CFB1 x => new TDES_CFB1(x),
				External.TDES_CFB64 x => new TDES_CFB64(x),
				External.TDES_CFB8 x => new TDES_CFB8(x),
				External.TDES_CFBP1 x => new TDES_CFBP1(x),
				External.TDES_CFBP64 x => new TDES_CFBP64(x),
				External.TDES_CFBP8 x => new TDES_CFBP8(x),
				External.TDES_CTR x => new TDES_CTR(x),
				External.TDES_ECB x => new TDES_ECB(x),
				External.TDES_KW x => new TDES_KW(x),
				External.TDES_OFB x => new TDES_OFB(x),
				External.TDES_OFBI x => new TDES_OFBI(x),
				External.TupleHash_128 x => new TupleHash_128(x),
				External.TupleHash_256 x => new TupleHash_256(x),
				_ => null
			};
		}
	}
}
