CREATE TABLE [common].[ADMIN_USER_ROLE] (
    [id]      BIGINT IDENTITY (1, 1) NOT NULL,
    [role_id] BIGINT NOT NULL,
    [user_id] BIGINT NOT NULL,
    CONSTRAINT [PK_ADMIN_USER_ROLE] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_ADMIN_USER_ROLE_ROLE_ID] FOREIGN KEY ([role_id]) REFERENCES [common].[ADMIN_ROLE] ([id]),
    CONSTRAINT [FK_ADMIN_USER_ROLE_USER_ID] FOREIGN KEY ([user_id]) REFERENCES [common].[ADMIN_USER] ([id]),
    CONSTRAINT [UQ_ADMIN_USER_ROLE_ROLE_USER] UNIQUE NONCLUSTERED ([role_id] ASC, [user_id] ASC)
);

