CREATE TABLE [common].[ADMIN_USER] (
    [id]       BIGINT        IDENTITY (1, 1) NOT NULL,
    [username] NVARCHAR (64) NOT NULL,
    CONSTRAINT [PK_ADMIN_USER] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_ADMIN_USER_USERNAME] UNIQUE NONCLUSTERED ([username] ASC)
);

