CREATE TABLE [common].[ADMIN_PERMISSION] (
    [id]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [permission_name] NVARCHAR (64) NOT NULL,
    CONSTRAINT [PK_ADMIN_PERMISSION] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_ADMIN_PERMISSION_PERMISSION_NAME] UNIQUE NONCLUSTERED ([permission_name] ASC)
);

