CREATE TABLE [common].[ADMIN_PERMISSION_ROLE] (
    [permission_id] BIGINT NOT NULL,
    [role_id]       BIGINT NOT NULL,
    CONSTRAINT [FK_ADMIN_PERMISSION_ROLE_PERMISSION_ID] FOREIGN KEY ([permission_id]) REFERENCES [common].[ADMIN_PERMISSION] ([id]),
    CONSTRAINT [FK_ADMIN_PERMISSION_ROLE_ROLE_ID] FOREIGN KEY ([role_id]) REFERENCES [common].[ADMIN_ROLE] ([id])
);

