CREATE TABLE [common].[ADMIN_ROLE] (
    [id]        BIGINT        IDENTITY (1, 1) NOT NULL,
    [role_name] NVARCHAR (64) NOT NULL,
    CONSTRAINT [PK_ADMIN_ROLE] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_ADMIN_ROLE_ROLE_NAME] UNIQUE NONCLUSTERED ([role_name] ASC)
);

