CREATE TABLE [common].[APPLICATION_PROPERTIES] (
    [id]    BIGINT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [name]  NVARCHAR (256)  NOT NULL,
    [value] NVARCHAR (2048) NOT NULL,
    [type]  NVARCHAR (10)   NOT NULL,
    CONSTRAINT [PK_APPLICATION_PROPERTIES] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_APPLICATION_PROPERTIES_NAME] UNIQUE NONCLUSTERED ([name] ASC)
);

