CREATE TABLE [acvp].[ACVP_USER_ROLE] (
    [id]      BIGINT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [role_id] BIGINT NOT NULL,
    [user_id] BIGINT NOT NULL,
    CONSTRAINT [PK_ACVP_USER_ROLE] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_ACVP_USER_ROLE_ROLE_USER] UNIQUE NONCLUSTERED ([role_id] ASC, [user_id] ASC)
);

