using System.ComponentModel;

namespace NIST.CVP.Crypto.Common
{
    /// <summary>
    /// Algorithm and Mode enum, algorithm and mode are 
    /// separated by a "-" or "_" in the Description/Value respectively.
    /// </summary>
    public enum AlgoMode
    {
        [Description("AES-CBC")]
        AES_CBC,
        [Description("AES-CCM")]
        AES_CCM,
        [Description("AES-CFB1")]
        AES_CFB1,
        [Description("AES-CFB8")]
        AES_CFB8,
        [Description("AES-CFB128")]
        AES_CFB128,
        [Description("AES-CTR")]
        AES_CTR,
        [Description("AES-ECB")]
        AES_ECB,
        [Description("AES-GCM")]
        AES_GCM,
        [Description("AES-KW")]
        AES_KW,
        [Description("AES-KWP")]
        AES_KWP,
        [Description("AES-OFB")]
        AES_OFB,
        [Description("AES-XPN")]
        AES_XPN,
        [Description("AES-XTS")]
        AES_XTS,
        [Description("CMAC-AES")]
        CMAC_AES,
        [Description("CMAC-TDES")]
        CMAC_TDES,
        [Description("ctrDRBG")]
        DRBG_CTR,
        [Description("hashDRBG")]
        DRBG_Hash,
        [Description("hmacDRBG")]
        DRBG_HMAC,
        [Description("DSA-KeyGen")]
        DSA_KeyGen,
        [Description("DSA-PQGGen")]
        DSA_PQGGen,
        [Description("DSA-PQGVer")]
        DSA_PQGVer,
        [Description("DSA-SigGen")]
        DSA_SigGen,
        [Description("DSA-SigVer")]
        DSA_SigVer,
        [Description("ECDSA-KeyGen")]
        ECDSA_KeyGen,
        [Description("ECDSA-KeyVer")]
        ECDSA_KeyVer,
        [Description("ECDSA-SigGen")]
        ECDSA_SigGen,
        [Description("ECDSA-SigVer")]
        ECDSA_SigVer,
        [Description("HMAC")]
        HMAC,
        [Description("KAS-ECC")]
        KAS_ECC,
        [Description("KAS-EccComponent")]
        KAS_EccComponent,
        [Description("KAS-FFC")]
        KAS_FFC,
        [Description("KDF")]
        KDF,
        [Description("KDF-Components-ANSIX9.64")]
        KDFComponents_ANSIX963,
        [Description("KDF-Components-IKEv1")]
        KDFComponents_IKEv1,
        [Description("KDF-Components-IKEv2")]
        KDFComponents_IKEv2,
        [Description("KDF-Components-SNMP")]
        KDFComponents_SNMP,
        [Description("KDF-Components-SRTP")]
        KDFComponents_SRTP,
        [Description("KDF-Components-SSH")]
        KDFComponents_SSH,
        [Description("KDF-Components-TLS")]
        KDFComponents_TLS,
        [Description("RSA-KeyGen")]
        RSA_KeyGen,
        [Description("RSA-SigGen")]
        RSA_SigGen,
        [Description("RSA-SigVer")]
        RSA_SigVer,
        [Description("SHA2")]
        SHA2,
        [Description("SHA3")]
        SHA3,
        [Description("SHAKE")]
        SHAKE,
        [Description("TDES-CBC")]
        TDES_CBC,
        [Description("TDES-CBCI")]
        TDES_CBCI,
        [Description("TDES-CFB1")]
        TDES_CFB1,
        [Description("TDES-CFB8")]
        TDES_CFB8,
        [Description("TDES-CFB64")]
        TDES_CFB64,
        [Description("TDES-CFBP1")]
        TDES_CFBP1,
        [Description("TDES-CFBP8")]
        TDES_CFBP8,
        [Description("TDES-CFBP64")]
        TDES_CFBP64,
        [Description("TDES-CTR")]
        TDES_CTR,
        [Description("TDES-ECB")]
        TDES_ECB,
        [Description("TDES-KW")]
        TDES_KW,
        [Description("TDES-OFB")]
        TDES_OFB,
        [Description("TDES-OFBI")]
        TDES_OFBI
    }
}