CREATE PROCEDURE [val].[OEExists]
	
	@OEId bigint

AS

SET NOCOUNT ON

SELECT CAST(CASE
		WHEN EXISTS (SELECT NULL
					 FROM val.VALIDATION_OE
					 WHERE id = @OEId) THEN 1
		ELSE 0
		END AS bit) AS [Exists]