

CREATE VIEW [csrc].[LEGACY_CRYPTO_ALGORITHM_FAMILY]
WITH SCHEMABINDING
AS

SELECT id, name, header_text
FROM ref.LEGACY_CRYPTO_ALGORITHM_FAMILY


GO
CREATE UNIQUE CLUSTERED INDEX [PK_CSRC_LEGACY_CRYPTO_ALGORITHM_FAMILY]
    ON [csrc].[LEGACY_CRYPTO_ALGORITHM_FAMILY]([id] ASC);

