CREATE VIEW [csrc].[STRING_VALUE_DISPLAY_MAPPING]
WITH SCHEMABINDING
AS

SELECT id, property_id, string_value, display_value
FROM ref.STRING_VALUE_DISPLAY_MAPPING


GO
CREATE UNIQUE CLUSTERED INDEX [PK_CSRC_STRING_VALUE_DISPLAY_MAPPING]
    ON [csrc].[STRING_VALUE_DISPLAY_MAPPING]([id] ASC);

