
CREATE VIEW [csrc].[VALIDATION_OE_DEPENDENCY_ATTRIBUTE]
WITH SCHEMABINDING
AS

SELECT id, validation_oe_dependency_id, name, value
FROM val.VALIDATION_OE_DEPENDENCY_ATTRIBUTE


GO
CREATE UNIQUE CLUSTERED INDEX [PK_CSRC_VALIDATION_OE_DEPENDENCY_ATTRIBUTE]
    ON [csrc].[VALIDATION_OE_DEPENDENCY_ATTRIBUTE]([id] ASC);

