CREATE VIEW [csrc].[VALIDATION_SCENARIO_ALGORITHM]
WITH SCHEMABINDING
AS

SELECT	 A.id
		,A.algorithm_id
		,A.scenario_id
FROM val.VALIDATION_SCENARIO_ALGORITHM A
	INNER JOIN
	val.VALIDATION_SCENARIO S ON S.id = A.scenario_id
	INNER JOIN
	val.VALIDATION_RECORD R ON R.id = S.record_id
	INNER JOIN
	val.PRODUCT_INFORMATION P ON P.id = R.product_information_id
							AND P.itar = 0

