
CREATE VIEW [csrc].[VALIDATION_SOURCE]
WITH SCHEMABINDING
AS

SELECT id, name, prefix
FROM val.VALIDATION_SOURCE


GO
CREATE UNIQUE CLUSTERED INDEX [PK_CSRC_VALIDATION_SOURCE]
    ON [csrc].[VALIDATION_SOURCE]([id] ASC);

