

CREATE VIEW [csrc].[VALIDATION_OE_DEPENDENCY]
WITH SCHEMABINDING
AS

SELECT id, dependency_type, name, description
FROM val.VALIDATION_OE_DEPENDENCY



GO
CREATE UNIQUE CLUSTERED INDEX [PK_CSRC_VALIDATION_OE_DEPENDENCY]
    ON [csrc].[VALIDATION_OE_DEPENDENCY]([id] ASC);

