CREATE TABLE [ref].[CRYPTO_ALGORITHM_LINK] (
    [algorithm_id]   BIGINT NOT NULL,
    [acv_version_id] INT    NOT NULL,
    CONSTRAINT [PK_CRYPTO_ALGORITHM_LINK] PRIMARY KEY CLUSTERED ([algorithm_id] ASC, [acv_version_id] ASC),
    CONSTRAINT [FK_CRYPTO_ALGORITHM_LINK_ACV_VERSION_ID] FOREIGN KEY ([acv_version_id]) REFERENCES [ref].[ACV_VERSION] ([id]),
    CONSTRAINT [FK_CRYPTO_ALGORITHM_LINK_ALGORITHM_ID] FOREIGN KEY ([algorithm_id]) REFERENCES [ref].[CRYPTO_ALGORITHM] ([id])
);

