CREATE TABLE [ref].[CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK] (
    [id]                   BIGINT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [acv_version_id]       INT    NOT NULL,
    [protocol_id]          BIGINT NOT NULL,
    [capability_parent_id] BIGINT NULL,
    [vector_parent_id]     BIGINT NULL,
    [group_parent_id]      BIGINT NULL,
    [value_parent_id]      BIGINT NULL,
    CONSTRAINT [PK_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK_ACV_VERSION_ID] FOREIGN KEY ([acv_version_id]) REFERENCES [ref].[ACV_VERSION] ([id]),
    CONSTRAINT [FK_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK_CAPABILITY_PARENT_ID] FOREIGN KEY ([capability_parent_id]) REFERENCES [ref].[CRYPTO_ALGORITHM_PROPERTY_PROTOCOL] ([id]),
    CONSTRAINT [FK_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK_GROUP_PARENT_ID] FOREIGN KEY ([group_parent_id]) REFERENCES [ref].[CRYPTO_ALGORITHM_PROPERTY_PROTOCOL] ([id]),
    CONSTRAINT [FK_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK_PROTOCOL_ID] FOREIGN KEY ([protocol_id]) REFERENCES [ref].[CRYPTO_ALGORITHM_PROPERTY_PROTOCOL] ([id]),
    CONSTRAINT [FK_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK_VALUE_PARENT_ID] FOREIGN KEY ([value_parent_id]) REFERENCES [ref].[CRYPTO_ALGORITHM_PROPERTY_PROTOCOL] ([id]),
    CONSTRAINT [FK_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK_VECTOR_PARENT_ID] FOREIGN KEY ([vector_parent_id]) REFERENCES [ref].[CRYPTO_ALGORITHM_PROPERTY_PROTOCOL] ([id]),
    CONSTRAINT [UQ_CRYPTO_ALGORITHM_PROPERTY_PROTOCOL_ACV_VERSION_LINK_VERSION_PROTOCOL] UNIQUE NONCLUSTERED ([acv_version_id] ASC, [protocol_id] ASC)
);

