CREATE TABLE [ref].[LEGACY_CRYPTO_ALGORITHM_FAMILY_LINK] (
    [family_id]    BIGINT NOT NULL,
    [algorithm_id] BIGINT NOT NULL,
    CONSTRAINT [PK_LEGACY_CRYPTO_ALGORITHM_FAMILY_LINK] PRIMARY KEY CLUSTERED ([family_id] ASC, [algorithm_id] ASC)
);

