CREATE TABLE [ref].[MODULE_TYPE] (
    [id]   INT           NOT NULL,
    [name] NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_MODULE_TYPE] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_MODULE_TYPE_NAME] UNIQUE NONCLUSTERED ([name] ASC)
);

