CREATE TABLE [ref].[PROPERTY_TYPE] (
    [id]   INT           NOT NULL,
    [name] NVARCHAR (25) NOT NULL,
    CONSTRAINT [PK_PROPERTY_TYPE] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UQ_PROPERTY_TYPE_NAME] UNIQUE NONCLUSTERED ([name] ASC)
);

