CREATE PROCEDURE [dbo].[OEExists]
	
	@OEId bigint

AS

SET NOCOUNT ON

SELECT CAST(CASE
		WHEN EXISTS (SELECT NULL
					 FROM dbo.OEs
					 WHERE OEId = @OEId) THEN 1
		ELSE 0
		END AS bit) AS [Exists]