using System.Text.Json;
using ACVPCore.Algorithms.External;

namespace ACVPCore.Algorithms
{
	public static class ExternalAlgorithmFactory
	{
		public static IExternalAlgorithm Deserialize(string algorithmRegistration)
		{
			//Deserialize the name/mode/revision by deserializing just to an AlgorithmBase
			AlgorithmBase algorithmBase = JsonSerializer.Deserialize<AlgorithmBase>(algorithmRegistration);

			//Get the type by a big old switch
			return (algorithmBase.Name, algorithmBase.Mode, algorithmBase.Revision) switch
			{
				("ACVP-AES-CBC", null, "1.0") => JsonSerializer.Deserialize<AES_CBC>(algorithmRegistration),
				("ACVP-AES-CBC-CS1", null, "1.0") => JsonSerializer.Deserialize<AES_CBC_CS1>(algorithmRegistration),
				("ACVP-AES-CBC-CS2", null, "1.0") => JsonSerializer.Deserialize<AES_CBC_CS2>(algorithmRegistration),
				("ACVP-AES-CBC-CS3", null, "1.0") => JsonSerializer.Deserialize<AES_CBC_CS3>(algorithmRegistration),
				("ACVP-AES-CCM", null, "1.0") => JsonSerializer.Deserialize<AES_CCM>(algorithmRegistration),
				("ACVP-AES-CFB1", null, "1.0") => JsonSerializer.Deserialize<AES_CFB1>(algorithmRegistration),
				("ACVP-AES-CFB128", null, "1.0") => JsonSerializer.Deserialize<AES_CFB128>(algorithmRegistration),
				("ACVP-AES-CFB8", null, "1.0") => JsonSerializer.Deserialize<AES_CFB8>(algorithmRegistration),
				("ACVP-AES-CTR", null, "1.0") => JsonSerializer.Deserialize<AES_CTR>(algorithmRegistration),
				("ACVP-AES-ECB", null, "1.0") => JsonSerializer.Deserialize<AES_ECB>(algorithmRegistration),
				("ACVP-AES-FF1", null, "1.0") => JsonSerializer.Deserialize<AES_FF1>(algorithmRegistration),
				("ACVP-AES-GCM", null, "1.0") => JsonSerializer.Deserialize<AES_GCM>(algorithmRegistration),
				("ACVP-AES-GMAC", null, "1.0") => JsonSerializer.Deserialize<AES_GMAC>(algorithmRegistration),
				("ACVP-AES-KW", null, "1.0") => JsonSerializer.Deserialize<AES_KW>(algorithmRegistration),
				("ACVP-AES-KWP", null, "1.0") => JsonSerializer.Deserialize<AES_KWP>(algorithmRegistration),
				("ACVP-AES-OFB", null, "1.0") => JsonSerializer.Deserialize<AES_OFB>(algorithmRegistration),
				("ACVP-AES-XPN", null, "1.0") => JsonSerializer.Deserialize<AES_XPN>(algorithmRegistration),
				("ACVP-AES-XTS", null, "1.0") => JsonSerializer.Deserialize<AES_XTS>(algorithmRegistration),
				("ACVP-TDES-CBC", null, "1.0") => JsonSerializer.Deserialize<TDES_CBC>(algorithmRegistration),
				("ACVP-TDES-CBCI", null, "1.0") => JsonSerializer.Deserialize<TDES_CBCI>(algorithmRegistration),
				("ACVP-TDES-CFB1", null, "1.0") => JsonSerializer.Deserialize<TDES_CFB1>(algorithmRegistration),
				("ACVP-TDES-CFB64", null, "1.0") => JsonSerializer.Deserialize<TDES_CFB64>(algorithmRegistration),
				("ACVP-TDES-CFB8", null, "1.0") => JsonSerializer.Deserialize<TDES_CFB8>(algorithmRegistration),
				("ACVP-TDES-CFBP1", null, "1.0") => JsonSerializer.Deserialize<TDES_CFBP1>(algorithmRegistration),
				("ACVP-TDES-CFBP64", null, "1.0") => JsonSerializer.Deserialize<TDES_CFBP64>(algorithmRegistration),
				("ACVP-TDES-CFBP8", null, "1.0") => JsonSerializer.Deserialize<TDES_CFBP8>(algorithmRegistration),
				("ACVP-TDES-CTR", null, "1.0") => JsonSerializer.Deserialize<TDES_CTR>(algorithmRegistration),
				("ACVP-TDES-ECB", null, "1.0") => JsonSerializer.Deserialize<TDES_ECB>(algorithmRegistration),
				("ACVP-TDES-KW", null, "1.0") => JsonSerializer.Deserialize<TDES_KW>(algorithmRegistration),
				("ACVP-TDES-OFB", null, "1.0") => JsonSerializer.Deserialize<TDES_OFB>(algorithmRegistration),
				("ACVP-TDES-OFBI", null, "1.0") => JsonSerializer.Deserialize<TDES_OFBI>(algorithmRegistration),
				("CMAC-AES", null, "1.0") => JsonSerializer.Deserialize<AES_CMAC>(algorithmRegistration),
				("ctrDRBG", null, "1.0") => JsonSerializer.Deserialize<CounterDRBG>(algorithmRegistration),
				("CSHAKE-128", null, "1.0") => JsonSerializer.Deserialize<CSHAKE_128>(algorithmRegistration),
				("CSHAKE-256", null, "1.0") => JsonSerializer.Deserialize<CSHAKE_256>(algorithmRegistration),
				("DSA", "keyGen", "1.0") => JsonSerializer.Deserialize<DSAKeyGen186_4>(algorithmRegistration),
				("DSA", "pqgGen", "1.0") => JsonSerializer.Deserialize<DSAPQGGen186_4>(algorithmRegistration),
				("DSA", "pqgVer", "1.0") => JsonSerializer.Deserialize<DSAPQGVer186_4>(algorithmRegistration),
				("DSA", "sigGen", "1.0") => JsonSerializer.Deserialize<DSASigGen186_4>(algorithmRegistration),
				("DSA", "sigVer", "1.0") => JsonSerializer.Deserialize<DSASigVer186_4>(algorithmRegistration),
				("ECDSA", "keyGen", "1.0") => JsonSerializer.Deserialize<ECDSAKeyGen186_4>(algorithmRegistration),
				("ECDSA", "keyVer", "1.0") => JsonSerializer.Deserialize<ECDSAKeyVer186_4>(algorithmRegistration),
				("ECDSA", "sigGen", "1.0") => JsonSerializer.Deserialize<ECDSASigGen186_4>(algorithmRegistration),
				("ECDSA", "sigVer", "1.0") => JsonSerializer.Deserialize<ECDSASigVer186_4>(algorithmRegistration),
				("hashDRBG", null, "1.0") => JsonSerializer.Deserialize<HashDRBG>(algorithmRegistration),
				("hmacDRBG", null, "1.0") => JsonSerializer.Deserialize<HMAC_DRBG>(algorithmRegistration),
				("HMAC-SHA-1", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA_1>(algorithmRegistration),
				("HMAC-SHA2-224", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA2_224>(algorithmRegistration),
				("HMAC-SHA2-256", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA2_256>(algorithmRegistration),
				("HMAC-SHA2-384", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA2_384>(algorithmRegistration),
				("HMAC-SHA2-512", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA2_512>(algorithmRegistration),
				("HMAC-SHA2-512/224", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA2_512224>(algorithmRegistration),
				("HMAC-SHA2-512/256", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA2_512256> (algorithmRegistration),
				("HMAC-SHA3-224", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA3_224>(algorithmRegistration),
				("HMAC-SHA3-256", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA3_256>(algorithmRegistration),
				("HMAC-SHA3-384", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA3_384>(algorithmRegistration),
				("HMAC-SHA3-512", null, "1.0") => JsonSerializer.Deserialize<HMAC_SHA3_512>(algorithmRegistration),
				("KAS-ECC", null, "1.0") => JsonSerializer.Deserialize<KAS_ECC>(algorithmRegistration),
				("KAS-ECC", "Component", "1.0") => JsonSerializer.Deserialize<KAS_ECC_Component>(algorithmRegistration),
				("KAS-ECC", "CDH-Component", "1.0") => JsonSerializer.Deserialize<KAS_ECC_CDH>(algorithmRegistration),
				("KAS-ECC", null, "Sp800-56Ar3") => JsonSerializer.Deserialize<KAS_ECC_SP800_56Ar3>(algorithmRegistration),
				("KAS-FFC", null, "1.0") => JsonSerializer.Deserialize<KAS_FFC>(algorithmRegistration),
				("KAS-FFC", null, "Sp800-56Ar3") => JsonSerializer.Deserialize<KAS_FFC_SP800_56Ar3>(algorithmRegistration),
				("KDF", null, "1.0") => JsonSerializer.Deserialize<KDF>(algorithmRegistration),
				("kdf-components", "ansix9.42", "1.0") => JsonSerializer.Deserialize<KDF_ANSIX942>(algorithmRegistration),
				("kdf-components", "ansix9.63", "1.0") => JsonSerializer.Deserialize<KDF_ANSIX963>(algorithmRegistration),
				("kdf-components", "ikev1", "1.0") => JsonSerializer.Deserialize<KDF_IKEv1>(algorithmRegistration),
				("kdf-components", "ikev2", "1.0") => JsonSerializer.Deserialize<KDF_IKEv2>(algorithmRegistration),
				("kdf-components", "pbkdf", "1.0") => JsonSerializer.Deserialize<KDF_PBKDF>(algorithmRegistration),
				("kdf-components", "snmp", "1.0") => JsonSerializer.Deserialize<KDF_SNMP>(algorithmRegistration),
				("kdf-components", "srtp", "1.0") => JsonSerializer.Deserialize<KDF_SRTP>(algorithmRegistration),
				("kdf-components", "ssh", "1.0") => JsonSerializer.Deserialize<KDF_SSH>(algorithmRegistration),
				("kdf-components", "tls", "1.0") => JsonSerializer.Deserialize<KDF_TLS>(algorithmRegistration),
				("kdf-components", "tpm", "1.0") => JsonSerializer.Deserialize<KDF_TPM>(algorithmRegistration),
				("KMAC-128", null, "1.0") => JsonSerializer.Deserialize<KMAC_128>(algorithmRegistration),
				("KMAC-256", null, "1.0") => JsonSerializer.Deserialize<KMAC_256>(algorithmRegistration),
				("PARALLELHASH-128", null, "1.0") => JsonSerializer.Deserialize<ParallelHash_128>(algorithmRegistration),
				("PARALLELHASH-256", null, "1.0") => JsonSerializer.Deserialize<ParallelHash_256>(algorithmRegistration),
				("RSA", "decryptionPrimitive", "1.0") => JsonSerializer.Deserialize<RSADecryptionPrimitive>(algorithmRegistration),
				("RSA", "signaturePrimitive", "1.0") => JsonSerializer.Deserialize<RSASignaturePrimitive>(algorithmRegistration),
				("RSA", "legacySigVer", "1.0") => JsonSerializer.Deserialize<RSASigVer186_2>(algorithmRegistration),
				("RSA", "keyGen", "186-2") => JsonSerializer.Deserialize<RSAKeyGen186_2>(algorithmRegistration),
				("RSA", "keyGen", "1.0") => JsonSerializer.Deserialize<RSAKeyGen186_4>(algorithmRegistration),
				("RSA", "sigGen", "186-2") => JsonSerializer.Deserialize<RSASigGen186_2>(algorithmRegistration),
				("RSA", "sigGen", "1.0") => JsonSerializer.Deserialize<RSASigGen186_4>(algorithmRegistration),
				("RSA", "sigVer", "1.0") => JsonSerializer.Deserialize<RSASigVer186_4>(algorithmRegistration),
				("safePrimes", "keyGen", "1.0") => JsonSerializer.Deserialize<SafePrimesKeyGen>(algorithmRegistration),
				("safePrimes", "keyVer", "1.0") => JsonSerializer.Deserialize<SafePrimesKeyVer>(algorithmRegistration),
				("SHA-1", null, "1.0") => JsonSerializer.Deserialize<SHA_1>(algorithmRegistration),
				("SHA2-224", null, "1.0") => JsonSerializer.Deserialize<SHA2_224>(algorithmRegistration),
				("SHA2-256", null, "1.0") => JsonSerializer.Deserialize<SHA2_256>(algorithmRegistration),
				("SHA2-384", null, "1.0") => JsonSerializer.Deserialize<SHA2_384>(algorithmRegistration),
				("SHA2-512", null, "1.0") => JsonSerializer.Deserialize<SHA2_512>(algorithmRegistration),
				("SHA2-512224", null, "1.0") => JsonSerializer.Deserialize<SHA2_512224>(algorithmRegistration),
				("SHA2-512256", null, "1.0") => JsonSerializer.Deserialize<SHA2_512256>(algorithmRegistration),
				("SHA3-224", null, "1.0") => JsonSerializer.Deserialize<SHA3_224>(algorithmRegistration),
				("SHA3-256", null, "1.0") => JsonSerializer.Deserialize<SHA3_256>(algorithmRegistration),
				("SHA3-384", null, "1.0") => JsonSerializer.Deserialize<SHA3_384>(algorithmRegistration),
				("SHA3-512", null, "1.0") => JsonSerializer.Deserialize<SHA3_512>(algorithmRegistration),
				("SHAKE-128", null, "1.0") => JsonSerializer.Deserialize<SHAKE_128>(algorithmRegistration),
				("SHAKE-256", null, "1.0") => JsonSerializer.Deserialize<SHAKE_256>(algorithmRegistration),
				("TUPLEHASH-128", null, "1.0") => JsonSerializer.Deserialize<TupleHash_128>(algorithmRegistration),
				("TUPLEHASH-256", null, "1.0") => JsonSerializer.Deserialize<TupleHash_256>(algorithmRegistration),
				_ => null
			};
		}

	}
}



