using ACVPCore.Algorithms.External;
using ACVPCore.Algorithms.Persisted;

namespace ACVPCore.Algorithms
{
	public static class PersistedAlgorithmFactory
	{
		public static IPersistedAlgorithm GetPersistedAlgorithm(IExternalAlgorithm externalAlgorithm)
		{
			//Get the type by a big old switch
			return externalAlgorithm switch
			{
				External.AES_CBC x => new Persisted.AES_CBC(x),
				External.AES_CBC_CS1 x => new Persisted.AES_CBC_CS1(x),
				External.AES_CBC_CS2 x => new Persisted.AES_CBC_CS2(x),
				External.AES_CBC_CS3 x => new Persisted.AES_CBC_CS3(x),
				External.AES_CCM x => new Persisted.AES_CCM(x),
				External.AES_CFB1 x => new Persisted.AES_CFB1(x),
				External.AES_CFB128 x => new Persisted.AES_CFB128(x),
				External.AES_CFB8 x => new Persisted.AES_CFB8(x),
				External.AES_CTR x => new Persisted.AES_CTR(x),
				External.AES_ECB x => new Persisted.AES_ECB(x),
				External.AES_FF1 x => new Persisted.AES_FF1(x),
				External.AES_GCM x => new Persisted.AES_GCM(x),
				External.AES_GMAC x => new Persisted.AES_GMAC(x),
				External.AES_KW x => new Persisted.AES_KW(x),
				External.AES_KWP x => new Persisted.AES_KWP(x),
				External.AES_OFB x => new Persisted.AES_OFB(x),
				External.AES_XPN x => new Persisted.AES_XPN(x),
				External.AES_XTS x => new Persisted.AES_XTS(x),
				External.AES_CMAC x => new Persisted.AES_CMAC(x),
				External.CounterDRBG x => new Persisted.CounterDRBG(x),
				External.CSHAKE_128 x => new Persisted.CSHAKE_128(x),
				External.CSHAKE_256 x => new Persisted.CSHAKE_256(x),
				External.DSAKeyGen186_4 x => new Persisted.DSAKeyGen186_4(x),
				External.DSAPQGGen186_4 x => new Persisted.DSAPQGGen186_4(x),
				External.DSAPQGVer186_4 x => new Persisted.DSAPQGVer186_4(x),
				External.DSASigGen186_4 x => new Persisted.DSASigGen186_4(x),
				External.DSASigVer186_4 x => new Persisted.DSASigVer186_4(x),
				External.ECDSAKeyGen186_4 x => new Persisted.ECDSAKeyGen186_4(x),
				External.ECDSAKeyVer186_4 x => new Persisted.ECDSAKeyVer186_4(x),
				External.ECDSASigGen186_4 x => new Persisted.ECDSASigGen186_4(x),
				External.ECDSASigVer186_4 x => new Persisted.ECDSASigVer186_4(x),
				External.HashDRBG x => new Persisted.HashDRBG(x),
				External.HMAC_DRBG x => new Persisted.HMAC_DRBG(x),
				External.HMAC_SHA_1 x => new Persisted.HMAC_SHA_1(x),
				External.HMAC_SHA2_224 x => new Persisted.HMAC_SHA2_224(x),
				External.HMAC_SHA2_256 x => new Persisted.HMAC_SHA2_256(x),
				External.HMAC_SHA2_384 x => new Persisted.HMAC_SHA2_384(x),
				External.HMAC_SHA2_512 x => new Persisted.HMAC_SHA2_512(x),
				External.HMAC_SHA2_512224 x => new Persisted.HMAC_SHA2_512224(x),
				External.HMAC_SHA2_512256 x => new Persisted.HMAC_SHA2_512256(x),
				External.HMAC_SHA3_224 x => new Persisted.HMAC_SHA3_224(x),
				External.HMAC_SHA3_256 x => new Persisted.HMAC_SHA3_256(x),
				External.HMAC_SHA3_384 x => new Persisted.HMAC_SHA3_384(x),
				External.HMAC_SHA3_512 x => new Persisted.HMAC_SHA3_512(x),
				External.KAS_ECC x => new Persisted.KAS_ECC(x),
				External.KAS_ECC_Component x => new Persisted.KAS_ECC_Component(x),
				External.KAS_ECC_CDH x => new Persisted.KAS_ECC_CDH(x),
				External.KAS_ECC_SP800_56Ar3 x => new Persisted.KAS_ECC_SP800_56Ar3(x),
				External.KAS_FFC x => new Persisted.KAS_FFC(x),
				External.KAS_FFC_SP800_56Ar3 x => new Persisted.KAS_FFC_SP800_56Ar3(x),
				External.KDF x => new Persisted.KDF(x),
				External.KDF_ANSIX942 x => new Persisted.KDF_ANSIX942(x),
				External.KDF_ANSIX963 x => new Persisted.KDF_ANSIX963(x),
				External.KDF_IKEv1 x => new Persisted.KDF_IKEv1(x),
				External.KDF_IKEv2 x => new Persisted.KDF_IKEv2(x),
				External.KDF_PBKDF x => new Persisted.KDF_PBKDF(x),
				External.KDF_SNMP x => new Persisted.KDF_SNMP(x),
				External.KDF_SRTP x => new Persisted.KDF_SRTP(x),
				External.KDF_SSH x => new Persisted.KDF_SSH(x),
				External.KDF_TLS x => new Persisted.KDF_TLS(x),
				External.KDF_TPM x => new Persisted.KDF_TPM(x),
				External.KMAC_128 x => new Persisted.KMAC_128(x),
				External.KMAC_256 x => new Persisted.KMAC_256(x),
				External.ParallelHash_128 x => new Persisted.ParallelHash_128(x),
				External.ParallelHash_256 x => new Persisted.ParallelHash_256(x),
				External.RSADecryptionPrimitive x => new Persisted.RSADecryptionPrimitive(x),
				External.RSASignaturePrimitive x => new Persisted.RSASignaturePrimitive(x),
				External.RSAKeyGen186_2 x => new Persisted.RSAKeyGen186_2(x),
				External.RSAKeyGen186_4 x => new Persisted.RSAKeyGen186_4(x),
				External.RSASigGen186_2 x => new Persisted.RSASigGen186_2(x),
				External.RSASigGen186_4 x => new Persisted.RSASigGen186_4(x),
				External.RSASigVer186_2 x => new Persisted.RSASigVer186_2(x),
				External.RSASigVer186_4 x => new Persisted.RSASigVer186_4(x),
				External.SafePrimesKeyGen x => new Persisted.SafePrimesKeyGen(x),
				External.SafePrimesKeyVer x => new Persisted.SafePrimesKeyVer(x),
				External.SHA_1 x => new Persisted.SHA_1(x),
				External.SHA2_224 x => new Persisted.SHA2_224(x),
				External.SHA2_256 x => new Persisted.SHA2_256(x),
				External.SHA2_384 x => new Persisted.SHA2_384(x),
				External.SHA2_512 x => new Persisted.SHA2_512(x),
				External.SHA2_512224 x => new Persisted.SHA2_512224(x),
				External.SHA2_512256 x => new Persisted.SHA2_512256(x),
				External.SHA3_224 x => new Persisted.SHA3_224(x),
				External.SHA3_256 x => new Persisted.SHA3_256(x),
				External.SHA3_384 x => new Persisted.SHA3_384(x),
				External.SHA3_512 x => new Persisted.SHA3_512(x),
				External.SHAKE_128 x => new Persisted.SHAKE_128(x),
				External.SHAKE_256 x => new Persisted.SHAKE_256(x),
				External.TDES_CBC x => new Persisted.TDES_CBC(x),
				External.TDES_CBCI x => new Persisted.TDES_CBCI(x),
				External.TDES_CFB1 x => new Persisted.TDES_CFB1(x),
				External.TDES_CFB64 x => new Persisted.TDES_CFB64(x),
				External.TDES_CFB8 x => new Persisted.TDES_CFB8(x),
				External.TDES_CFBP1 x => new Persisted.TDES_CFBP1(x),
				External.TDES_CFBP64 x => new Persisted.TDES_CFBP64(x),
				External.TDES_CFBP8 x => new Persisted.TDES_CFBP8(x),
				External.TDES_CTR x => new Persisted.TDES_CTR(x),
				External.TDES_ECB x => new Persisted.TDES_ECB(x),
				External.TDES_KW x => new Persisted.TDES_KW(x),
				External.TDES_OFB x => new Persisted.TDES_OFB(x),
				External.TDES_OFBI x => new Persisted.TDES_OFBI(x),
				External.TupleHash_128 x => new Persisted.TupleHash_128(x),
				External.TupleHash_256 x => new Persisted.TupleHash_256(x),
				_ => null
			};
		}
	}
}
